LEFT_PAREN_TOKEN = '('
RIGHT_PAREN_TOKEN = ')'
SEMICOLON_TOKEN = ';'
COMMA_TOKEN = ','

SPACE_TOKEN = ' '

UNSIGNED_TOKEN = 'unsigned'
SIGNED_TOKEN = 'signed'

INT_TOKEN = 'int'
CHAR_TOKEN = 'char'
SHORT_TOKEN = 'short'
LONG_TOKEN = 'long'

FLOAT_TOKEN = 'float'
DOUBLE_TOKEN = 'double'
BOOL_TOKEN = 'bool'

RESERVED_WORDS = [INT_TOKEN, CHAR_TOKEN, SHORT_TOKEN,
                  LONG_TOKEN, FLOAT_TOKEN, DOUBLE_TOKEN, BOOL_TOKEN]
